import os
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
DB_PATH = Path(os.environ.get("SKILLTRACKER_DB", BASE_DIR / "skilltracker.sqlite3"))


POSTGRES_MIGRATIONS = {
    1: (
        """
        CREATE TABLE users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email TEXT NOT NULL,
            password_hash TEXT NOT NULL,
            is_admin BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL
        )
        """,
        "CREATE UNIQUE INDEX users_email_lower_unique ON users (LOWER(email))",
        """
        CREATE TABLE sessions (
            token_hash TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            expires_at TIMESTAMPTZ NOT NULL
        )
        """,
        """
        CREATE TABLE settings (
            user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
            study_board TEXT NOT NULL DEFAULT ''
        )
        """,
        """
        CREATE TABLE skills (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            category TEXT NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            risk_level REAL NOT NULL DEFAULT 5,
            difficulty REAL NOT NULL DEFAULT 5,
            language_code TEXT NOT NULL DEFAULT 'en-US',
            initial_score REAL NOT NULL DEFAULT 1,
            accuracy_score REAL NOT NULL DEFAULT 0.7,
            speed_score REAL NOT NULL DEFAULT 0.7,
            marking_criteria TEXT NOT NULL DEFAULT '',
            last_practiced TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL
        )
        """,
        "CREATE INDEX skills_user ON skills(user_id)",
        """
        CREATE TABLE practices (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            skill_id INTEGER NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
            scenario TEXT NOT NULL,
            response TEXT NOT NULL,
            evaluation_json TEXT NOT NULL,
            readiness_score REAL NOT NULL,
            readiness_after REAL NOT NULL DEFAULT 0,
            submission_id TEXT,
            elapsed_seconds INTEGER NOT NULL,
            created_at TIMESTAMPTZ NOT NULL
        )
        """,
        "CREATE INDEX practices_user_created ON practices(user_id, created_at DESC)",
        "CREATE UNIQUE INDEX practices_user_submission ON practices(user_id, submission_id) WHERE submission_id IS NOT NULL",
    ),
    2: (
        """
        CREATE TABLE IF NOT EXISTS ai_diagnostics (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ NOT NULL,
            task TEXT NOT NULL CHECK (task IN ('scenario', 'feedback', 'connectivity_test')),
            success BOOLEAN NOT NULL,
            error_category TEXT,
            http_status SMALLINT,
            model TEXT NOT NULL,
            latency_ms INTEGER NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
            fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
            safe_message TEXT
        )
        """,
        "CREATE INDEX IF NOT EXISTS ai_diagnostics_created_at ON ai_diagnostics(created_at DESC)",
        "CREATE INDEX IF NOT EXISTS ai_diagnostics_task_created_at ON ai_diagnostics(task, created_at DESC)",
    ),
}


class DatabaseConnection:
    def __init__(self, connection, postgres):
        self._connection = connection
        self.is_postgres = postgres

    def _sql(self, statement):
        return statement.replace("?", "%s") if self.is_postgres else statement

    def _parameters(self, parameters):
        if self.is_postgres:
            return parameters
        return tuple(value.isoformat(timespec="seconds") if isinstance(value, datetime) else value for value in parameters)

    def execute(self, statement, parameters=()):
        return self._connection.execute(self._sql(statement), self._parameters(parameters))

    def executemany(self, statement, parameter_rows):
        cursor = self._connection.cursor()
        cursor.executemany(self._sql(statement), (self._parameters(row) for row in parameter_rows))
        return cursor

    def executescript(self, script):
        if self.is_postgres:
            raise RuntimeError("PostgreSQL migrations execute versioned statements individually.")
        return self._connection.executescript(script)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def database_backend():
    return "postgresql" if os.environ.get("DATABASE_URL", "").strip() else "sqlite"


def database_configuration():
    if database_backend() == "postgresql":
        return {"backend": "postgresql", "configured": True, "path_type": "database_url_env"}
    configured_path = bool(os.environ.get("SKILLTRACKER_DB", "").strip())
    return {
        "backend": "sqlite",
        "configured": configured_path,
        "path_type": "configured_env" if configured_path else "default",
    }


def _connect():
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if database_url:
        import psycopg
        from psycopg.rows import dict_row

        connection = psycopg.connect(database_url, row_factory=dict_row, connect_timeout=10)
        return DatabaseConnection(connection, postgres=True)
    if os.environ.get("RENDER", "").lower() == "true" or os.environ.get("RENDER_SERVICE_ID"):
        raise RuntimeError("DATABASE_URL must be configured for Render PostgreSQL deployment.")
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(DB_PATH, timeout=10)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return DatabaseConnection(connection, postgres=False)


@contextmanager
def connect_db():
    connection = _connect()
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def _initialize_sqlite():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with connect_db() as db:
        db.executescript("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY,
                email TEXT NOT NULL UNIQUE COLLATE NOCASE,
                password_hash TEXT NOT NULL,
                is_admin INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS sessions (
                token_hash TEXT PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                expires_at TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS settings (
                user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                study_board TEXT NOT NULL DEFAULT ''
            );
            CREATE TABLE IF NOT EXISTS skills (
                id INTEGER PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                name TEXT NOT NULL,
                category TEXT NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                risk_level REAL NOT NULL DEFAULT 5,
                difficulty REAL NOT NULL DEFAULT 5,
                language_code TEXT NOT NULL DEFAULT 'en-US',
                initial_score REAL NOT NULL DEFAULT 1,
                accuracy_score REAL NOT NULL DEFAULT 0.7,
                speed_score REAL NOT NULL DEFAULT 0.7,
                marking_criteria TEXT NOT NULL DEFAULT '',
                last_practiced TEXT,
                created_at TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS practices (
                id INTEGER PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                skill_id INTEGER NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
                scenario TEXT NOT NULL,
                response TEXT NOT NULL,
                evaluation_json TEXT NOT NULL,
                readiness_score REAL NOT NULL,
                readiness_after REAL NOT NULL DEFAULT 0,
                submission_id TEXT,
                elapsed_seconds INTEGER NOT NULL,
                created_at TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS ai_diagnostics (
                id INTEGER PRIMARY KEY,
                created_at TEXT NOT NULL,
                task TEXT NOT NULL CHECK (task IN ('scenario', 'feedback', 'connectivity_test')),
                success INTEGER NOT NULL,
                error_category TEXT,
                http_status INTEGER,
                model TEXT NOT NULL,
                latency_ms INTEGER NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
                fallback_used INTEGER NOT NULL DEFAULT 0,
                safe_message TEXT
            );
            CREATE INDEX IF NOT EXISTS practices_user_created ON practices(user_id, created_at DESC);
            CREATE INDEX IF NOT EXISTS skills_user ON skills(user_id);
            CREATE INDEX IF NOT EXISTS ai_diagnostics_created_at ON ai_diagnostics(created_at DESC);
            CREATE INDEX IF NOT EXISTS ai_diagnostics_task_created_at ON ai_diagnostics(task, created_at DESC);
        """)
        practice_columns = {row["name"] for row in db.execute("PRAGMA table_info(practices)")}
        if "readiness_after" not in practice_columns:
            db.execute("ALTER TABLE practices ADD COLUMN readiness_after REAL NOT NULL DEFAULT 0")
        skill_columns = {row["name"] for row in db.execute("PRAGMA table_info(skills)")}
        if "language_code" not in skill_columns:
            db.execute("ALTER TABLE skills ADD COLUMN language_code TEXT NOT NULL DEFAULT 'en-US'")
        if "description" not in skill_columns:
            db.execute("ALTER TABLE skills ADD COLUMN description TEXT NOT NULL DEFAULT ''")
        if "submission_id" not in practice_columns:
            db.execute("ALTER TABLE practices ADD COLUMN submission_id TEXT")
        db.execute("CREATE UNIQUE INDEX IF NOT EXISTS practices_user_submission ON practices(user_id, submission_id) WHERE submission_id IS NOT NULL")


def _initialize_postgres():
    with connect_db() as db:
        db.execute("CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)")
        applied = {row["version"] for row in db.execute("SELECT version FROM schema_migrations").fetchall()}
        for version, statements in sorted(POSTGRES_MIGRATIONS.items()):
            if version in applied:
                continue
            for statement in statements:
                db.execute(statement)
            db.execute("INSERT INTO schema_migrations(version) VALUES(?)", (version,))


def initialize_db():
    if database_backend() == "postgresql":
        _initialize_postgres()
    else:
        _initialize_sqlite()


def record_ai_diagnostic(diagnostic):
    allowed_tasks = {"scenario", "feedback", "connectivity_test"}
    task = diagnostic.get("task")
    if task not in allowed_tasks:
        raise ValueError("Unsupported AI diagnostic task.")
    safe_values = (
        now_timestamp(),
        task,
        bool(diagnostic["success"]),
        diagnostic.get("error_category"),
        diagnostic.get("http_status"),
        diagnostic["model"],
        max(0, int(diagnostic.get("latency_ms", 0))),
        bool(diagnostic.get("fallback_used", False)),
        diagnostic.get("safe_message"),
    )
    with connect_db() as db:
        db.execute(
            "INSERT INTO ai_diagnostics(created_at,task,success,error_category,http_status,model,latency_ms,fallback_used,safe_message) VALUES(?,?,?,?,?,?,?,?,?)",
            safe_values,
        )


def now_timestamp():
    return datetime.now(timezone.utc).replace(microsecond=0)


def is_integrity_error(error):
    if isinstance(error, sqlite3.IntegrityError):
        return True
    try:
        import psycopg
    except ImportError:
        return False
    return isinstance(error, psycopg.IntegrityError)